### ISSUE TITLE
org.gnome.desktop.background has no 'draw-background' key anymore

### ISSUE THREAD

**Issue by manuelbua** [l3ib/nitrogen#43]
It looks like the schema coming with Gnome 3.10 doesn't support the 'draw-background' key anymore, so the gnome backend (setbg) will not work.

**Comment by daf** [comment]
I think this is fixed somewhere around 5de50201, can re-open if not true

**Comment by daf** [comment]
Looks like several people still having this issue (see #43, #91)

**Comment by daf** [comment]
Added a better guarding mechanism for those who don't have this key. Mine still has it, marked as deprecated.  :man_shrugging:

**Comment by gudbjornv** [comment]
I'm still getting this error `Settings schema 'org.gnome.desktop.background' does not contain a key named 'draw-background'` when trying to set the wallpaper. Running Manjaro.

**Comment by actualdankcoder** [comment]
Still getting this error on Arch 5.15.5

**Comment by ttrreevvoorr** [comment]
Sorry to say I have experienced this on Debian XFCE for the better part of the last year or so.
